# Generated by Django 4.2.3 on 2023-07-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_classificationhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificationhistory',
            old_name='date_time',
            new_name='classification_date',
        ),
        migrations.RenameField(
            model_name='classificationhistory',
            old_name='file_name',
            new_name='music_file_name',
        ),
        migrations.AlterField(
            model_name='classificationhistory',
            name='classified_genre',
            field=models.CharField(max_length=255),
        ),
    ]
